---
driver:
  name: digitalocean

platforms:
  - name: centos-6-5-x64

suites:
  - name: default
    run_list:
      - recipe[wordpress]
    attributes:
      mysql:
        server_root_password: "Please-Dont-Use-In-Production"
        server_debian_password: "Please-Dont-Use-In-Production"
        server_repl_password: "Please-Dont-Use-In-Production"
  - name: nginx
    run_list:
      - recipe[wordpress::nginx]
    attributes:
      mysql:
        server_root_password: "Please-Dont-Use-In-Production"
        server_debian_password: "Please-Dont-Use-In-Production"
        server_repl_password: "Please-Dont-Use-In-Production"
